# Generated by Django 4.0.2 on 2022-03-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_page_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(default='a320751238b7474aa63356bbea73b479', max_length=32, unique=True),
        ),
    ]
