# Generated by Django 4.0.2 on 2022-03-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_page_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(default='e06487f368db498b97cb5b70ae4267cf', max_length=32, unique=True),
        ),
    ]
