# Generated by Django 4.0.2 on 2022-03-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_page_follow_requests_page_followers_page_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, related_name='followRequest', to='mainapp.Page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to='mainapp.Page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='user_following', to='mainapp.Page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(default='86c2bfdb023e41bc8e75fe8f44a17026', max_length=32, unique=True),
        ),
    ]
