# Generated by Django 4.0.2 on 2022-03-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_page_follow_requests_alter_page_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(default='d7b27cdff7fb480eb462f85519554a62', max_length=32, unique=True),
        ),
    ]
