# Generated by Django 4.0.2 on 2022-03-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_page_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='parent',
        ),
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(default='9ae417ff3f424bb2ad2c6d2ed1f706b8', max_length=32, unique=True),
        ),
    ]
