# Generated by Django 4.0.3 on 2022-03-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_page_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(default='9975ff0af0a048528263fc858cbad74d', max_length=32, unique=True),
        ),
    ]
