version: '3.8'

services:
  web:
    build:
      context: innotter/
      dockerfile: Dockerfile
    volumes:
      - .:/innotter
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=innotter
      - POSTGRES_PASSWORD=innotter
      - POSTGRES_DB=innotter_dev

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
    depends_on:
      - web
      - celery
      - db

  redis:
    image: redis:alpine

  celery:
    build: ./innotter
    restart: always
    command: celery -A app.celery worker --pool=solo --loglevel=info  # celery -A innotter worker -l info
    volumes:
      - ./innotter:/innotter
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
