version: '3.8'

services:
  web:
    build:
      context: innotter/
      dockerfile: Dockerfile
    volumes:
      - .:/innotter
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=innotter
      - POSTGRES_PASSWORD=innotter
      - POSTGRES_DB=innotter_dev
  redis:
    image: redis:alpine
  celery:
    build: ./innotter
    restart: always
    command: celery -A app.celery worker --pool=solo --loglevel=info  # celery -A innotter worker -l info
    volumes:
      - ./innotter:/innotter
#    environment:
#      - POSTGRES_USER=innotter
#      - POSTGRES_PASSWORD=innotter
#      - POSTGRES_DB=innotter_dev
    env_file:
      - ./.env
    depends_on:
      - redis
#      - db
#      - web
volumes:
  postgres_data:
