# Generated by Django 4.0.2 on 2022-03-10 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotterapp', '0005_alter_page_uuid'),
        ('content_interaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagefollowing',
            name='following_page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='innotterapp.page'),
        ),
        migrations.AlterField(
            model_name='pagefollowing',
            name='page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='innotterapp.page'),
        ),
    ]
