# Generated by Django 4.0.2 on 2022-03-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_interaction', '0002_alter_pagefollowing_following_page_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageFollowing',
        ),
    ]
