# Generated by Django 4.0.2 on 2022-03-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(default='326999674f884130b7bdf058b04becec', max_length=32, unique=True),
        ),
    ]
