# Generated by Django 4.0.2 on 2022-03-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotterapp', '0010_alter_page_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(default='48c21f93530d4f99ad46537b2fe3fdcc', max_length=32, unique=True),
        ),
    ]
