# Generated by Django 4.0.3 on 2022-03-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotterapp', '0011_alter_page_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(default='8695cb9018464cd2a949afadaaeafae5', max_length=32, unique=True),
        ),
    ]
