# Generated by Django 4.0.3 on 2022-03-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotterapp', '0012_alter_page_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(default='862084f207a64167ad3509a430896698', max_length=32, unique=True),
        ),
    ]
