# Generated by Django 4.0.3 on 2022-03-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innotterapp', '0013_alter_page_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(default='a8999244c5774120849a223b03e7263b', max_length=32, unique=True),
        ),
    ]
