# Generated by Django 4.0.2 on 2022-03-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_s3_path',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
